# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec15d9f45029c4006596eb7ed17ce10a4207491723c97554c3681da7aa67499146044ecb7dbac5f63aef16ea2dc59bf0e7545108704f70a41fa4f9d9d158887

test:
  secret_key_base: f4bb3651dff4e3e562ffbbc3093ce08f1dc4304fcebc9e40c32a6219d3a37e0bbdc3bb1ae51ca35caac812155084e0d9ff8ba9788e0025151ceb46f35feb15cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # TODO generate secret key for each installation and provide to server on start
  secret_key_base: <%= defined? JRUBY_VERSION ? java.lang.System.getProperty('secret_key_base') : ENV["SECRET_KEY_BASE"] %>
